name: jxvier
favicon: null
layout_spectrum: 0.4678017876576632
typography_spectrum: 0.3281838984694332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 0.7534966887906194
  saturation: 0.5146995522081852
  rhythmicContrast: 0.14397925278171897
purpose: []
